# Generated by Django 6.0.7 on 2026-07-28 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.userexperiment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'user_experiment', 'delivery_date'), name='unique_daily_reminder')],
            },
        ),
    ]
