# Generated by Django 6.0.7 on 2026-07-28 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_intent', models.PositiveSmallIntegerField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_reflection', to='experiments.userexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('energy', models.PositiveSmallIntegerField()),
                ('curiosity', models.PositiveSmallIntegerField()),
                ('meaning', models.PositiveSmallIntegerField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('minutes_spent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='experiments.userexperiment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_experiment', 'day'), name='unique_daily_checkin')],
            },
        ),
    ]
