# Generated by Django 6.0.7 on 2026-08-09 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0003_experimenttrait_experimenttraitweight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('min_experiments', models.PositiveSmallIntegerField(default=2)),
                ('min_fit_score', models.PositiveSmallIntegerField(default=70)),
                ('positive_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('traits', models.ManyToManyField(related_name='pattern_definitions', to='experiments.experimenttrait')),
            ],
        ),
        migrations.CreateModel(
            name='TraitEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experiment_trait_weight', models.PositiveSmallIntegerField()),
                ('evidence_weight', models.DecimalField(decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_evidence', to='experiments.experimenttrait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_evidence', to=settings.AUTH_USER_MODEL)),
                ('user_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_evidence', to='experiments.userexperiment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_experiment', 'trait'), name='uq_trait_evidence_per_run')],
            },
        ),
        migrations.CreateModel(
            name='UserHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uncertain', 'Uncertain'), ('emerging', 'Emerging'), ('supported', 'Supported'), ('contradicted', 'Contradicted')], default='uncertain', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hypotheses', to='experiments.experimenttrait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'trait'), name='uq_user_trait_hypothesis')],
            },
        ),
    ]
